stdno=int(input("Enter student number: "))
stdName=input("Enter student name: ")
phy=int(input("Enter phy marks: "))
maths=int(input("Enter maths marks: "))
eng=int(input("Enter eng marks: "))
total=(phy+maths+eng)
average=round(total/3,2)
print("StdNo    StdName    Phy    Maths    eng    total    average")
print(stdno,stdName,phy,maths,eng,total,average, sep="      ")